export const seoKeywords = {
  title: "WEETOO | Live Trading Broadcast · Highest Self-Referral Payback",
  description:
    "The first live trading broadcast & demo trading community in Korea, WEETOO! Officially partnered with Binance, Bybit, OKX, Bitget, BingX, and LBank. From skill sharing and live broadcasts to the highest self-referral payback — enjoy all the benefits in one place with WEETOO!",
  keywords: [
    "Weetoo",
    "Weetoo trading",
    "Weetoo platform",
    "Weetoo company",
    "Weetoo trading platform",
    "Weetoo trading community",
    "Weetoo trading simulation",
    "Weetoo trading rooms",
    "Weetoo trading competition",
    "Weetoo trading education",
    "Weetoo trading tools",
    "Weetoo trading app",
    "Weetoo trading software",
    "Weetoo trading signals",
    "Weetoo trading mentorship",
    "Weetoo trading courses",
    "Weetoo trading analytics",
    "Weetoo trading performance",
    "Weetoo trading strategies",
    "Weetoo trading psychology",
    "Weetoo risk management",
    "Weetoo portfolio management",
    "Weetoo market analysis",
    "Weetoo real-time data",
    "Weetoo cryptocurrency trading",
    "Weetoo forex trading",
    "Weetoo stock trading",
    "Weetoo crypto exchange",
    "Weetoo trading bot",
    "Weetoo automated trading",
    "Weetoo social trading",
    "Weetoo copy trading",
    "Weetoo paper trading",
    "Weetoo virtual trading",
    "Weetoo live trading",
    "Weetoo trading charts",
    "Weetoo trading indicators",
    "Weetoo trading tools",
    "Weetoo mobile trading",
    "Weetoo web trading",
    "Weetoo financial technology",
    "Weetoo fintech",
    "Weetoo digital assets",
    "Weetoo blockchain trading",
    "Weetoo decentralized trading",
    "Weetoo market research",
    "Weetoo economic indicators",
    "Weetoo profit tracking",
    "Weetoo loss prevention",
    "Weetoo trading discipline",
    "trading platform",
    "cryptocurrency trading",
    "forex trading",
    "stock trading",
    "risk-free trading",
    "trading simulation",
    "real-time market data",
    "trading community",
    "investment platform",
    "trading education",
    "paper trading",
    "virtual trading",
    "trading competition",
    "trading rooms",
    "live trading",
    "trading signals",
    "market analysis",
    "trading tools",
    "trading charts",
    "trading indicators",
    "portfolio management",
    "trading strategies",
    "financial markets",
    "crypto exchange",
    "trading bot",
    "automated trading",
    "social trading",
    "copy trading",
    "trading mentorship",
    "trading courses",
    "financial education",
    "investment learning",
    "trading psychology",
    "risk management",
    "trading software",
    "mobile trading",
    "web trading",
    "trading app",
    "financial technology",
    "fintech",
    "digital assets",
    "blockchain trading",
    "decentralized trading",
    "trading analytics",
    "market research",
    "economic indicators",
    "trading performance",
    "profit tracking",
    "loss prevention",
    "trading discipline",

    "위투",
    "WEETOO",
    "트레이딩 커뮤니티",
    "모의투자 플랫폼",
    "실시간 투자 방송",
    "페이백 커뮤니티",
    "셀퍼럴",
    "셀퍼럴 페이백",
    "최고 요율 페이백",
    "바이낸스",
    "Binance",
    "바이낸스 페이백",
    "Binance payback",
    "바이비트",
    "Bybit",
    "바이비트 페이백",
    "Bybit payback",
    "OKX",
    "OKX 페이백",
    "Bitget",
    "비트겟",
    "Bitget payback",
    "비트겟 페이백",
    "BingX",
    "빙엑스",
    "BingX payback",
    "빙엑스 페이백",
    "LBank",
    "엘뱅크",
    "LBank payback",
    "엘뱅크 페이백",
    "Gate.io",
    "게이트아이오",
    "Gate.io payback",
    "게이트아이오 페이백",
    "거래소 페이백",
    "Exchange payback",
    "Copy trading",
    "카피트레이딩",
    "트레이더 커뮤니티",
    "Trader community",
    "투자 커뮤니티",
    "Investment community",
    "코인판",
    "코인선물방송",
    "선물방송",
    "코인방송",
    "투자방송",
    "트레이딩방송",
    "코인트레이딩",
    "코갤",
    "코인갤러리",
    "테더맥스",
    "Sigbit",
    "시그비트",
    "거래소페이백",
    "테더페이백",
    "코비",
    "위프",
    "더따리",
    "테더메이트",
    "셀퍼페이백",
    "테더백",
    "셀퍼럴엑스",
    "오렌지X 페이백",
    "OrangeX payback",
    "탭비트 페이백",
    "Tapbit payback",
    "딥코인 페이백",
    "Deepcoin payback",
  ],
  openGraph: {
    title: "WEETOO | Live Trading Broadcast · Highest Self-Referral Payback",
    description:
      "The first live trading broadcast & demo trading community in Korea, WEETOO! Officially partnered with Binance, Bybit, OKX, Bitget, BingX, and LBank. From skill sharing and live broadcasts to the highest self-referral payback — enjoy all the benefits in one place with WEETOO!",
    type: "website",
    locale: "en_US",
    siteName: "Weetoo",
  },
  twitter: {
    card: "summary_large_image",
    title: "WEETOO | Live Trading Broadcast · Highest Self-Referral Payback",
    description:
      "The first live trading broadcast & demo trading community in Korea, WEETOO! Officially partnered with Binance, Bybit, OKX, Bitget, BingX, and LBank. From skill sharing and live broadcasts to the highest self-referral payback — enjoy all the benefits in one place with WEETOO!",
  },
};
