export const seoKeywords = {
  title: "Weetoo - Next-Gen Trading Platform",
  description:
    "Experience next-generation trading with Weetoo. Join our community for risk-free trading simulation, real-time market data, and collaborative learning.",
  keywords: [
    "Weetoo",
    "Weetoo trading",
    "Weetoo platform",
    "Weetoo company",
    "Weetoo trading platform",
    "Weetoo trading community",
    "Weetoo trading simulation",
    "Weetoo trading rooms",
    "Weetoo trading competition",
    "Weetoo trading education",
    "Weetoo trading tools",
    "Weetoo trading app",
    "Weetoo trading software",
    "Weetoo trading signals",
    "Weetoo trading mentorship",
    "Weetoo trading courses",
    "Weetoo trading analytics",
    "Weetoo trading performance",
    "Weetoo trading strategies",
    "Weetoo trading psychology",
    "Weetoo risk management",
    "Weetoo portfolio management",
    "Weetoo market analysis",
    "Weetoo real-time data",
    "Weetoo cryptocurrency trading",
    "Weetoo forex trading",
    "Weetoo stock trading",
    "Weetoo crypto exchange",
    "Weetoo trading bot",
    "Weetoo automated trading",
    "Weetoo social trading",
    "Weetoo copy trading",
    "Weetoo paper trading",
    "Weetoo virtual trading",
    "Weetoo live trading",
    "Weetoo trading charts",
    "Weetoo trading indicators",
    "Weetoo trading tools",
    "Weetoo mobile trading",
    "Weetoo web trading",
    "Weetoo financial technology",
    "Weetoo fintech",
    "Weetoo digital assets",
    "Weetoo blockchain trading",
    "Weetoo decentralized trading",
    "Weetoo market research",
    "Weetoo economic indicators",
    "Weetoo profit tracking",
    "Weetoo loss prevention",
    "Weetoo trading discipline",
    "trading platform",
    "cryptocurrency trading",
    "forex trading",
    "stock trading",
    "risk-free trading",
    "trading simulation",
    "real-time market data",
    "trading community",
    "investment platform",
    "trading education",
    "paper trading",
    "virtual trading",
    "trading competition",
    "trading rooms",
    "live trading",
    "trading signals",
    "market analysis",
    "trading tools",
    "trading charts",
    "trading indicators",
    "portfolio management",
    "trading strategies",
    "financial markets",
    "crypto exchange",
    "trading bot",
    "automated trading",
    "social trading",
    "copy trading",
    "trading mentorship",
    "trading courses",
    "financial education",
    "investment learning",
    "trading psychology",
    "risk management",
    "trading software",
    "mobile trading",
    "web trading",
    "trading app",
    "financial technology",
    "fintech",
    "digital assets",
    "blockchain trading",
    "decentralized trading",
    "trading analytics",
    "market research",
    "economic indicators",
    "trading performance",
    "profit tracking",
    "loss prevention",
    "trading discipline",
  ],
  openGraph: {
    title: "Weetoo - Next-Gen Trading Platform",
    description:
      "Experience next-generation trading with Weetoo. Join our community for risk-free trading simulation, real-time market data, and collaborative learning.",
    type: "website",
    locale: "en_US",
    siteName: "Weetoo",
  },
  twitter: {
    card: "summary_large_image",
    title: "Weetoo - Next-Gen Trading Platform",
    description:
      "Experience next-generation trading with Weetoo. Join our community for risk-free trading simulation, real-time market data, and collaborative learning.",
  },
};
