export interface UserData {
  id: string;
  name: string;
  uid: string;
  email: string;
  maskedEmail: string;
  status: "active" | "inactive" | "suspended" | "pending";
  warnings: number;
  korCoin: number;
  registered: string;
  lastLogin: string;
  role: "user" | "admin" | "super_admin";
  location: string;
  avatar?: string;
  totalTransactions: number;
  referrals: number;
}

export const mockUsers: UserData[] = [
  {
    id: "1",
    name: "John Doe",
    uid: "UID001",
    email: "john.doe@example.com",
    maskedEmail: "j***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 1250,
    registered: "2024-01-15",
    lastLogin: "2024-12-07",
    role: "admin",
    location: "New York, US",
    totalTransactions: 45,
    referrals: 12,
  },
  {
    id: "2",
    name: "Sarah Wilson",
    uid: "UID002",
    email: "sarah.wilson@example.com",
    maskedEmail: "s***@example.com",
    status: "active",
    warnings: 1,
    korCoin: 890,
    registered: "2024-02-20",
    lastLogin: "2024-12-06",
    role: "user",
    location: "London, UK",
    totalTransactions: 23,
    referrals: 5,
  },
  {
    id: "3",
    name: "Mike Johnson",
    uid: "UID003",
    email: "mike.johnson@example.com",
    maskedEmail: "m***@example.com",
    status: "suspended",
    warnings: 3,
    korCoin: 0,
    registered: "2024-03-10",
    lastLogin: "2024-11-28",
    role: "user",
    location: "Toronto, CA",
    totalTransactions: 8,
    referrals: 0,
  },
  {
    id: "4",
    name: "Emily Chen",
    uid: "UID004",
    email: "emily.chen@example.com",
    maskedEmail: "e***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 2100,
    registered: "2023-12-05",
    lastLogin: "2024-12-07",
    role: "super_admin",
    location: "Singapore, SG",
    totalTransactions: 67,
    referrals: 28,
  },
  {
    id: "5",
    name: "David Brown",
    uid: "UID005",
    email: "david.brown@example.com",
    maskedEmail: "d***@example.com",
    status: "pending",
    warnings: 0,
    korCoin: 50,
    registered: "2024-12-01",
    lastLogin: "2024-12-05",
    role: "user",
    location: "Sydney, AU",
    totalTransactions: 2,
    referrals: 1,
  },
  {
    id: "6",
    name: "Alice Cooper",
    uid: "UID006",
    email: "alice.cooper@example.com",
    maskedEmail: "a***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 1800,
    registered: "2024-01-20",
    lastLogin: "2024-12-07",
    role: "admin",
    location: "Berlin, DE",
    totalTransactions: 52,
    referrals: 18,
  },
  {
    id: "7",
    name: "Robert Smith",
    uid: "UID007",
    email: "robert.smith@example.com",
    maskedEmail: "r***@example.com",
    status: "active",
    warnings: 2,
    korCoin: 750,
    registered: "2024-03-15",
    lastLogin: "2024-12-06",
    role: "user",
    location: "Paris, FR",
    totalTransactions: 31,
    referrals: 7,
  },
  {
    id: "8",
    name: "Lisa Wang",
    uid: "UID008",
    email: "lisa.wang@example.com",
    maskedEmail: "l***@example.com",
    status: "inactive",
    warnings: 0,
    korCoin: 320,
    registered: "2024-04-10",
    lastLogin: "2024-11-15",
    role: "user",
    location: "Tokyo, JP",
    totalTransactions: 15,
    referrals: 3,
  },
  {
    id: "9",
    name: "James Wilson",
    uid: "UID009",
    email: "james.wilson@example.com",
    maskedEmail: "j***@example.com",
    status: "active",
    warnings: 1,
    korCoin: 1450,
    registered: "2023-11-20",
    lastLogin: "2024-12-07",
    role: "admin",
    location: "Melbourne, AU",
    totalTransactions: 38,
    referrals: 14,
  },
  {
    id: "10",
    name: "Maria Garcia",
    uid: "UID010",
    email: "maria.garcia@example.com",
    maskedEmail: "m***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 980,
    registered: "2024-02-28",
    lastLogin: "2024-12-06",
    role: "user",
    location: "Madrid, ES",
    totalTransactions: 27,
    referrals: 9,
  },
  {
    id: "11",
    name: "Kevin Lee",
    uid: "UID011",
    email: "kevin.lee@example.com",
    maskedEmail: "k***@example.com",
    status: "suspended",
    warnings: 4,
    korCoin: 0,
    registered: "2024-05-12",
    lastLogin: "2024-10-20",
    role: "user",
    location: "Seoul, KR",
    totalTransactions: 12,
    referrals: 2,
  },
  {
    id: "12",
    name: "Anna Petrov",
    uid: "UID012",
    email: "anna.petrov@example.com",
    maskedEmail: "a***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 1650,
    registered: "2023-10-08",
    lastLogin: "2024-12-07",
    role: "admin",
    location: "Moscow, RU",
    totalTransactions: 43,
    referrals: 16,
  },
  {
    id: "13",
    name: "Tom Anderson",
    uid: "UID013",
    email: "tom.anderson@example.com",
    maskedEmail: "t***@example.com",
    status: "pending",
    warnings: 0,
    korCoin: 100,
    registered: "2024-11-25",
    lastLogin: "2024-12-05",
    role: "user",
    location: "Vancouver, CA",
    totalTransactions: 3,
    referrals: 0,
  },
  {
    id: "14",
    name: "Sophie Martin",
    uid: "UID014",
    email: "sophie.martin@example.com",
    maskedEmail: "s***@example.com",
    status: "active",
    warnings: 1,
    korCoin: 1200,
    registered: "2024-01-30",
    lastLogin: "2024-12-06",
    role: "user",
    location: "Lyon, FR",
    totalTransactions: 35,
    referrals: 11,
  },
  {
    id: "15",
    name: "Alex Thompson",
    uid: "UID015",
    email: "alex.thompson@example.com",
    maskedEmail: "a***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 2500,
    registered: "2023-09-15",
    lastLogin: "2024-12-07",
    role: "super_admin",
    location: "San Francisco, US",
    totalTransactions: 78,
    referrals: 32,
  },
  {
    id: "16",
    name: "Rachel Green",
    uid: "UID016",
    email: "rachel.green@example.com",
    maskedEmail: "r***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 850,
    registered: "2024-06-12",
    lastLogin: "2024-12-06",
    role: "user",
    location: "Chicago, US",
    totalTransactions: 19,
    referrals: 4,
  },
  {
    id: "17",
    name: "Daniel Kim",
    uid: "UID017",
    email: "daniel.kim@example.com",
    maskedEmail: "d***@example.com",
    status: "inactive",
    warnings: 1,
    korCoin: 420,
    registered: "2024-07-08",
    lastLogin: "2024-11-10",
    role: "user",
    location: "Busan, KR",
    totalTransactions: 11,
    referrals: 1,
  },
  {
    id: "18",
    name: "Isabella Rodriguez",
    uid: "UID018",
    email: "isabella.rodriguez@example.com",
    maskedEmail: "i***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 1350,
    registered: "2024-02-14",
    lastLogin: "2024-12-07",
    role: "admin",
    location: "Barcelona, ES",
    totalTransactions: 41,
    referrals: 15,
  },
  {
    id: "19",
    name: "Michael O'Connor",
    uid: "UID019",
    email: "michael.oconnor@example.com",
    maskedEmail: "m***@example.com",
    status: "suspended",
    warnings: 5,
    korCoin: 0,
    registered: "2024-08-20",
    lastLogin: "2024-09-15",
    role: "user",
    location: "Dublin, IE",
    totalTransactions: 6,
    referrals: 0,
  },
  {
    id: "20",
    name: "Yuki Tanaka",
    uid: "UID020",
    email: "yuki.tanaka@example.com",
    maskedEmail: "y***@example.com",
    status: "active",
    warnings: 0,
    korCoin: 1750,
    registered: "2023-12-22",
    lastLogin: "2024-12-07",
    role: "admin",
    location: "Osaka, JP",
    totalTransactions: 56,
    referrals: 21,
  },
];
